### ISSUE TITLE
NNs are better than that

### ISSUE THREAD

**Issue by michaelklachko** [arogozhnikov/arogozhnikov.github.io#13]
This is a comment about your results from [Reconstructing pictures with ML](https://arogozhnikov.github.io/2016/02/09/DrawingPictureWithML.html)
NNs are not too bad if you make them bigger and use ReLU instead of Tanh (using Karpathy's [demo](https://cs.stanford.edu/people/karpathy/convnetjs/demo/image_regression.html)):
![image](https://user-images.githubusercontent.com/981619/93688086-0e3b2c80-fa78-11ea-84b4-91adcf4c7940.png)

An interesting question is how well the other ML methods scale compared to NNs.

**Comment by arogozhnikov** [comment]
yup, yup, I know NNs can do much better, but thanks for pointing :)  good quality was not priority - it is about visualizing what decision rules are like in each case. For this purpose it works well enough.

**Comment by arogozhnikov** [comment]
From perspective of what's working better: stuff like SIREN or deep image prior  would work much better than even Andrej's example (well,  what once was considered an example too far from having any application due to computational complexity eventually turned into research area).

Bur covering that is another large post (not sure I have time for that)
